# Generated by Django 4.2.8 on 2023-12-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_created=True, auto_now_add=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
